### ISSUE TITLE
Voice notes in simulator

### ISSUE THREAD

**Issue by NikolaTesla17** [shainotshy1/NoteIt#2]
Not sure if possible, research needed

**Comment by NikolaTesla17** [comment]
impossible: https://developer.android.com/guide/topics/media/mediarecorder

workarounds include bluestacks(untested), https://www.apkonline.net/ (untested) and using another app version once we gat around to those

**Comment by NikolaTesla17** [comment]
probably best to just work on other versions and assume it will work for now, maybe for our next project or something we could do react.js as it is cleaner in these scenarios, but for now this should work

**Comment by shainotshy1** [comment]
ok cool, for now I'm just testing by redownloading it on my own phone when it comes to testing the voice recording stuff. works so far
